# action name
name: 'globalprotect'

# action author
author: 'Bhaskar KC <xlinkerz@gmail.com>'

# action description
description: 'GlobalProtect connection'

# action runner
runs:
  using: 'docker'
  image: 'Dockerfile'

# branding
branding:
  icon: terminal
