on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Global Protect
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect
        uses: "./"
        env:
          USER: ${{ secrets.GB_USERNAME }}
          PASS: ${{ secrets.GB_PASSWORD }}
          SERVER: ${{ secrets.GB_SERVER }}
      - name: Check if connected
        run: curl -v ${{ secrets.TEST_SERVER }}
