on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Global Protect
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect
        uses: "./"
        with:
          user: ${{ secrets.GB_USERNAME }}
          pass: ${{ secrets.GB_PASSWORD }}
          server: ${{ secrets.GB_SERVER }}
      - name: Check if connected
        run: curl -v ${{ secrets.TEST_SERVER }}
